.\"*****************************************************************************
.\"                                                                            *
.\"   Author:      G. Leber                                                    *
.\"                Technische Universitaet Wien                                *
.\"                Institut fuer Technische Informatik E182/1                  *
.\"                Treitlstrasse 3                                             *
.\"                1040 Wien                                                   *
.\"                Tel.: (0222) 58801 / 8176                                   *
.\"                                                                            *
.\"****************************************************************************/
.TH SEM182 3 "RELEASE 2.4" "" "The sem182 library"
.SH NAME
seminit, semgrab, P, V, semrm \- Semaphore operations
.SH SYNTAX
.nf
.B #include <sem182.h>
.LP
.B int seminit (key_t key, int semperm, int initval);
.B int semgrab (key_t key);
.B int P (int semid);
.B int V (int semid);
.B int semrm (int semid);
.fi
.SH DESCRIPTION
These functions are easier to use than the standard interface.
.LP
.I seminit
creates a semaphore with 
.I key
using
.I semperm
as permissions and initializes the semaphore to
.I initval.
On success this function returns a valid descriptor for the semaphore.  In
case a semaphore with the specified key already exists,
.I seminit
returns -1.
.LP
.I semgrab
delivers a valid descriptor for an 
.B already existing
semaphore.
.LP
.I P
waits for the semaphore given by
.I semid.
.LP
.I V
signals to the semaphore given by
.I semid.
.LP
.I semrm
removes the semaphore given by
.I semid.
.SH DIAGNOSTICS
All functions return -1 in case of error.
.SH COMPILING
You have to specify the library to the compiler, e.g.
.LP
c89 program.c 
.B -lsem182
.SH SEE ALSO
semget(2), semop(2), semctl(2), msem182(3)
.SH DISCLAIMER
The sem182 library is provided "as is" for education purposes      
only. There is no warranty for the correct functionality and we do not          
accept any responsibility whatsoever for any loss or damage that is caused      
by the use of the sem182 library.
.SH AUTHORS
Implemented by Guenther Leber, Heinz Kantz and Raimund Kirner. Tested by Peter Holzer.
.LP
Manual page written by by Guenther Leber. Cleaned-up and reformatted by
Thomas Perl.
.SH THANKS
Many thanks go to Gerhard J. Fohler for inventing the name
.I semgrab
and to Gustav Pospischil for stomping around in our room and providing us
with no coffee and no cakes (we didn't ask him for coffee and cakes, but he
didn't bring them anyway :-).  Also thanks to Alexander Vrchoticky for
optimizing semgrab.
